export const searchFlightsResponse = {
  status: true,
  timestamp: 1752498255771,
  data: {
    context: {
      status: "incomplete",
      sessionId:
        "KLUv_WAwAB0HAObQMyKwqQPMCQNFWGTGOUnKVBizVUhl2nKnlKYXFlVBezPpV9sRKgAqACoALZfR3UpsELfVZA5BYZol85f6zyN89Bl2K0aVkMMoylfsHiclkqIBLIsUj7I3pI-99eV63bnb17__8a9CchI2ypIJMNiHJDKBMI9ruUrde9Wo2DYM3R6uxu_zcdkIlgfA7CdbEGtQsyM7N65oGRlqRl-m2HrvpEPaJrBASWEyCYRiiJy_tRZz66J-N2T2-qgZtc2GGI2G49C4SqVKGT9tXKWNjpuxBQUAX1iccT2uQcMbNlzgTEkB",
      totalResults: 10,
    },
    itineraries: [
      {
        id: "13554-2507160815--32171-0-12712-2507161128",
        price: {
          raw: 1261.34,
          formatted: "$1,262",
          pricingOptionId: "EVdiAFiNZct0",
        },
        legs: [
          {
            id: "13554-2507160815--32171-0-12712-2507161128",
            origin: {
              id: "LHR",
              entityId: "95565050",
              name: "London Heathrow",
              displayCode: "LHR",
              city: "London",
              country: "United Kingdom",
              isHighlighted: false,
            },
            destination: {
              id: "JFK",
              entityId: "95565058",
              name: "New York John F. Kennedy",
              displayCode: "JFK",
              city: "New York",
              country: "United States",
              isHighlighted: false,
            },
            durationInMinutes: 493,
            stopCount: 0,
            isSmallestStops: false,
            departure: "2025-07-16T08:15:00",
            arrival: "2025-07-16T11:28:00",
            timeDeltaInDays: 0,
            carriers: {
              marketing: [
                {
                  id: -32171,
                  alternateId: "B6",
                  logoUrl:
                    "https://logos.skyscnr.com/images/airlines/favicon/B6.png",
                  name: "jetBlue",
                },
              ],
              operationType: "fully_operated",
            },
            segments: [
              {
                id: "13554-12712-2507160815-2507161128--32171",
                origin: {
                  flightPlaceId: "LHR",
                  displayCode: "LHR",
                  parent: {
                    flightPlaceId: "LOND",
                    displayCode: "LON",
                    name: "London",
                    type: "City",
                  },
                  name: "London Heathrow",
                  type: "Airport",
                  country: "United Kingdom",
                },
                destination: {
                  flightPlaceId: "JFK",
                  displayCode: "JFK",
                  parent: {
                    flightPlaceId: "NYCA",
                    displayCode: "NYC",
                    name: "New York",
                    type: "City",
                  },
                  name: "New York John F. Kennedy",
                  type: "Airport",
                  country: "United States",
                },
                departure: "2025-07-16T08:15:00",
                arrival: "2025-07-16T11:28:00",
                durationInMinutes: 493,
                flightNumber: "2220",
                marketingCarrier: {
                  id: -32171,
                  name: "jetBlue",
                  alternateId: "B6",
                  allianceId: 0,
                  displayCode: "B6",
                },
                operatingCarrier: {
                  id: -32171,
                  name: "jetBlue",
                  alternateId: "B6",
                  allianceId: 0,
                  displayCode: "B6",
                },
                transportMode: "TRANSPORT_MODE_FLIGHT",
              },
            ],
          },
        ],
        isSelfTransfer: false,
        isProtectedSelfTransfer: false,
        farePolicy: {
          isChangeAllowed: false,
          isPartiallyChangeable: false,
          isCancellationAllowed: false,
          isPartiallyRefundable: false,
        },
        fareAttributes: {},
        tags: ["second_shortest"],
        isMashUp: false,
        hasFlexibleOptions: false,
        score: 0.999,
      },
      {
        id: "13542-2507161305--30598-0-12712-2507161555",
        price: {
          raw: 1348.63,
          formatted: "$1,349",
          pricingOptionId: "Zpe_sV9UoPYK",
        },
        legs: [
          {
            id: "13542-2507161305--30598-0-12712-2507161555",
            origin: {
              id: "LGW",
              entityId: "95565051",
              name: "London Gatwick",
              displayCode: "LGW",
              city: "London",
              country: "United Kingdom",
              isHighlighted: false,
            },
            destination: {
              id: "JFK",
              entityId: "95565058",
              name: "New York John F. Kennedy",
              displayCode: "JFK",
              city: "New York",
              country: "United States",
              isHighlighted: false,
            },
            durationInMinutes: 470,
            stopCount: 0,
            isSmallestStops: false,
            departure: "2025-07-16T13:05:00",
            arrival: "2025-07-16T15:55:00",
            timeDeltaInDays: 0,
            carriers: {
              marketing: [
                {
                  id: -30598,
                  alternateId: "I)",
                  logoUrl:
                    "https://logos.skyscnr.com/images/airlines/favicon/I%29.png",
                  name: "Norse Atlantic Airways (UK)",
                },
              ],
              operationType: "fully_operated",
            },
            segments: [
              {
                id: "13542-12712-2507161305-2507161555--30598",
                origin: {
                  flightPlaceId: "LGW",
                  displayCode: "LGW",
                  parent: {
                    flightPlaceId: "LOND",
                    displayCode: "LON",
                    name: "London",
                    type: "City",
                  },
                  name: "London Gatwick",
                  type: "Airport",
                  country: "United Kingdom",
                },
                destination: {
                  flightPlaceId: "JFK",
                  displayCode: "JFK",
                  parent: {
                    flightPlaceId: "NYCA",
                    displayCode: "NYC",
                    name: "New York",
                    type: "City",
                  },
                  name: "New York John F. Kennedy",
                  type: "Airport",
                  country: "United States",
                },
                departure: "2025-07-16T13:05:00",
                arrival: "2025-07-16T15:55:00",
                durationInMinutes: 470,
                flightNumber: "701",
                marketingCarrier: {
                  id: -30598,
                  name: "Norse Atlantic Airways (UK)",
                  alternateId: "I)",
                  allianceId: 0,
                  displayCode: "Z0",
                },
                operatingCarrier: {
                  id: -30598,
                  name: "Norse Atlantic Airways (UK)",
                  alternateId: "I)",
                  allianceId: 0,
                  displayCode: "Z0",
                },
                transportMode: "TRANSPORT_MODE_FLIGHT",
              },
            ],
          },
        ],
        isSelfTransfer: false,
        isProtectedSelfTransfer: false,
        farePolicy: {
          isChangeAllowed: false,
          isPartiallyChangeable: false,
          isCancellationAllowed: false,
          isPartiallyRefundable: false,
        },
        fareAttributes: {},
        tags: ["shortest"],
        isMashUp: false,
        hasFlexibleOptions: false,
        score: 0.883994,
      },
      {
        id: "13554-2507161020--31901-1-12712-2507161700",
        price: {
          raw: 937.94,
          formatted: "$938",
          pricingOptionId: "yQ4UOjfnTo7K",
        },
        legs: [
          {
            id: "13554-2507161020--31901-1-12712-2507161700",
            origin: {
              id: "LHR",
              entityId: "95565050",
              name: "London Heathrow",
              displayCode: "LHR",
              city: "London",
              country: "United Kingdom",
              isHighlighted: false,
            },
            destination: {
              id: "JFK",
              entityId: "95565058",
              name: "New York John F. Kennedy",
              displayCode: "JFK",
              city: "New York",
              country: "United States",
              isHighlighted: false,
            },
            durationInMinutes: 700,
            stopCount: 1,
            isSmallestStops: false,
            departure: "2025-07-16T10:20:00",
            arrival: "2025-07-16T17:00:00",
            timeDeltaInDays: 0,
            carriers: {
              marketing: [
                {
                  id: -31901,
                  alternateId: "SK",
                  logoUrl:
                    "https://logos.skyscnr.com/images/airlines/favicon/SK.png",
                  name: "Scandinavian Airlines",
                },
              ],
              operationType: "fully_operated",
            },
            segments: [
              {
                id: "13554-10694-2507161020-2507161310--31901",
                origin: {
                  flightPlaceId: "LHR",
                  displayCode: "LHR",
                  parent: {
                    flightPlaceId: "LOND",
                    displayCode: "LON",
                    name: "London",
                    type: "City",
                  },
                  name: "London Heathrow",
                  type: "Airport",
                  country: "United Kingdom",
                },
                destination: {
                  flightPlaceId: "CPH",
                  displayCode: "CPH",
                  parent: {
                    flightPlaceId: "COPE",
                    displayCode: "CPH",
                    name: "Copenhagen",
                    type: "City",
                  },
                  name: "Copenhagen",
                  type: "Airport",
                  country: "Denmark",
                },
                departure: "2025-07-16T10:20:00",
                arrival: "2025-07-16T13:10:00",
                durationInMinutes: 110,
                flightNumber: "502",
                marketingCarrier: {
                  id: -31901,
                  name: "Scandinavian Airlines",
                  alternateId: "SK",
                  allianceId: -31998,
                  displayCode: "SK",
                },
                operatingCarrier: {
                  id: -31901,
                  name: "Scandinavian Airlines",
                  alternateId: "SK",
                  allianceId: -31998,
                  displayCode: "SK",
                },
                transportMode: "TRANSPORT_MODE_FLIGHT",
              },
              {
                id: "10694-12712-2507161420-2507161700--31901",
                origin: {
                  flightPlaceId: "CPH",
                  displayCode: "CPH",
                  parent: {
                    flightPlaceId: "COPE",
                    displayCode: "CPH",
                    name: "Copenhagen",
                    type: "City",
                  },
                  name: "Copenhagen",
                  type: "Airport",
                  country: "Denmark",
                },
                destination: {
                  flightPlaceId: "JFK",
                  displayCode: "JFK",
                  parent: {
                    flightPlaceId: "NYCA",
                    displayCode: "NYC",
                    name: "New York",
                    type: "City",
                  },
                  name: "New York John F. Kennedy",
                  type: "Airport",
                  country: "United States",
                },
                departure: "2025-07-16T14:20:00",
                arrival: "2025-07-16T17:00:00",
                durationInMinutes: 520,
                flightNumber: "915",
                marketingCarrier: {
                  id: -31901,
                  name: "Scandinavian Airlines",
                  alternateId: "SK",
                  allianceId: -31998,
                  displayCode: "SK",
                },
                operatingCarrier: {
                  id: -31901,
                  name: "Scandinavian Airlines",
                  alternateId: "SK",
                  allianceId: -31998,
                  displayCode: "SK",
                },
                transportMode: "TRANSPORT_MODE_FLIGHT",
              },
            ],
          },
        ],
        isSelfTransfer: false,
        isProtectedSelfTransfer: false,
        farePolicy: {
          isChangeAllowed: false,
          isPartiallyChangeable: false,
          isCancellationAllowed: false,
          isPartiallyRefundable: false,
        },
        fareAttributes: {},
        isMashUp: false,
        hasFlexibleOptions: false,
        score: 0.780811,
      },
      {
        id: "13554-2507160705--31901-1-11442-2507161315",
        price: {
          raw: 920.5,
          formatted: "$921",
          pricingOptionId: "kCzb029sTzYK",
        },
        legs: [
          {
            id: "13554-2507160705--31901-1-11442-2507161315",
            origin: {
              id: "LHR",
              entityId: "95565050",
              name: "London Heathrow",
              displayCode: "LHR",
              city: "London",
              country: "United Kingdom",
              isHighlighted: false,
            },
            destination: {
              id: "EWR",
              entityId: "95565059",
              name: "New York Newark",
              displayCode: "EWR",
              city: "New York",
              country: "United States",
              isHighlighted: false,
            },
            durationInMinutes: 670,
            stopCount: 1,
            isSmallestStops: false,
            departure: "2025-07-16T07:05:00",
            arrival: "2025-07-16T13:15:00",
            timeDeltaInDays: 0,
            carriers: {
              marketing: [
                {
                  id: -31901,
                  alternateId: "SK",
                  logoUrl:
                    "https://logos.skyscnr.com/images/airlines/favicon/SK.png",
                  name: "Scandinavian Airlines",
                },
              ],
              operationType: "fully_operated",
            },
            segments: [
              {
                id: "13554-15093-2507160705-2507161010--31901",
                origin: {
                  flightPlaceId: "LHR",
                  displayCode: "LHR",
                  parent: {
                    flightPlaceId: "LOND",
                    displayCode: "LON",
                    name: "London",
                    type: "City",
                  },
                  name: "London Heathrow",
                  type: "Airport",
                  country: "United Kingdom",
                },
                destination: {
                  flightPlaceId: "OSL",
                  displayCode: "OSL",
                  parent: {
                    flightPlaceId: "OSLO",
                    displayCode: "OSL",
                    name: "Oslo",
                    type: "City",
                  },
                  name: "Oslo Gardermoen",
                  type: "Airport",
                  country: "Norway",
                },
                departure: "2025-07-16T07:05:00",
                arrival: "2025-07-16T10:10:00",
                durationInMinutes: 125,
                flightNumber: "802",
                marketingCarrier: {
                  id: -31901,
                  name: "Scandinavian Airlines",
                  alternateId: "SK",
                  allianceId: -31998,
                  displayCode: "SK",
                },
                operatingCarrier: {
                  id: -31901,
                  name: "Scandinavian Airlines",
                  alternateId: "SK",
                  allianceId: -31998,
                  displayCode: "SK",
                },
                transportMode: "TRANSPORT_MODE_FLIGHT",
              },
              {
                id: "15093-11442-2507161100-2507161315--31901",
                origin: {
                  flightPlaceId: "OSL",
                  displayCode: "OSL",
                  parent: {
                    flightPlaceId: "OSLO",
                    displayCode: "OSL",
                    name: "Oslo",
                    type: "City",
                  },
                  name: "Oslo Gardermoen",
                  type: "Airport",
                  country: "Norway",
                },
                destination: {
                  flightPlaceId: "EWR",
                  displayCode: "EWR",
                  parent: {
                    flightPlaceId: "NYCA",
                    displayCode: "NYC",
                    name: "New York",
                    type: "City",
                  },
                  name: "New York Newark",
                  type: "Airport",
                  country: "United States",
                },
                departure: "2025-07-16T11:00:00",
                arrival: "2025-07-16T13:15:00",
                durationInMinutes: 495,
                flightNumber: "907",
                marketingCarrier: {
                  id: -31901,
                  name: "Scandinavian Airlines",
                  alternateId: "SK",
                  allianceId: -31998,
                  displayCode: "SK",
                },
                operatingCarrier: {
                  id: -31901,
                  name: "Scandinavian Airlines",
                  alternateId: "SK",
                  allianceId: -31998,
                  displayCode: "SK",
                },
                transportMode: "TRANSPORT_MODE_FLIGHT",
              },
            ],
          },
        ],
        isSelfTransfer: false,
        isProtectedSelfTransfer: false,
        farePolicy: {
          isChangeAllowed: false,
          isPartiallyChangeable: false,
          isCancellationAllowed: false,
          isPartiallyRefundable: false,
        },
        fareAttributes: {},
        isMashUp: false,
        hasFlexibleOptions: false,
        score: 0.648417,
      },
      {
        id: "16574-2507161305--31915,-30667-1-12712-2507162200",
        price: {
          raw: 703.52,
          formatted: "$704",
          pricingOptionId: "5q0i2TOZMo8x",
        },
        legs: [
          {
            id: "16574-2507161305--31915,-30667-1-12712-2507162200",
            origin: {
              id: "STN",
              entityId: "95565052",
              name: "London Stansted",
              displayCode: "STN",
              city: "London",
              country: "United Kingdom",
              isHighlighted: false,
            },
            destination: {
              id: "JFK",
              entityId: "95565058",
              name: "New York John F. Kennedy",
              displayCode: "JFK",
              city: "New York",
              country: "United States",
              isHighlighted: false,
            },
            durationInMinutes: 835,
            stopCount: 1,
            isSmallestStops: false,
            departure: "2025-07-16T13:05:00",
            arrival: "2025-07-16T22:00:00",
            timeDeltaInDays: 0,
            carriers: {
              marketing: [
                {
                  id: -31915,
                  alternateId: "FR",
                  logoUrl:
                    "https://logos.skyscnr.com/images/airlines/favicon/FR.png",
                  name: "Ryanair",
                },
                {
                  id: -30667,
                  alternateId: "9~",
                  logoUrl:
                    "https://logos.skyscnr.com/images/airlines/favicon/9%7E.png",
                  name: "Norse Atlantic Airways",
                },
              ],
              operating: [
                {
                  id: -30823,
                  alternateId: "7A",
                  logoUrl:
                    "https://logos.skyscnr.com/images/airlines/favicon/7A.png",
                  name: "Malta Air",
                },
                {
                  id: -30667,
                  alternateId: "9~",
                  logoUrl:
                    "https://logos.skyscnr.com/images/airlines/favicon/9%7E.png",
                  name: "Norse Atlantic Airways",
                },
              ],
              operationType: "partially_operated",
            },
            segments: [
              {
                id: "16574-9828-2507161305-2507161550--31915",
                origin: {
                  flightPlaceId: "STN",
                  displayCode: "STN",
                  parent: {
                    flightPlaceId: "LOND",
                    displayCode: "LON",
                    name: "London",
                    type: "City",
                  },
                  name: "London Stansted",
                  type: "Airport",
                  country: "United Kingdom",
                },
                destination: {
                  flightPlaceId: "BER",
                  displayCode: "BER",
                  parent: {
                    flightPlaceId: "BERL",
                    displayCode: "BER",
                    name: "Berlin",
                    type: "City",
                  },
                  name: "Berlin Brandenburg",
                  type: "Airport",
                  country: "Germany",
                },
                departure: "2025-07-16T13:05:00",
                arrival: "2025-07-16T15:50:00",
                durationInMinutes: 105,
                flightNumber: "145",
                marketingCarrier: {
                  id: -31915,
                  name: "Ryanair",
                  alternateId: "FR",
                  allianceId: 0,
                  displayCode: "FR",
                },
                operatingCarrier: {
                  id: -30823,
                  name: "Malta Air",
                  alternateId: "7A",
                  allianceId: 0,
                  displayCode: "MAY",
                },
                transportMode: "TRANSPORT_MODE_FLIGHT",
              },
              {
                id: "9828-12712-2507161920-2507162200--30667",
                origin: {
                  flightPlaceId: "BER",
                  displayCode: "BER",
                  parent: {
                    flightPlaceId: "BERL",
                    displayCode: "BER",
                    name: "Berlin",
                    type: "City",
                  },
                  name: "Berlin Brandenburg",
                  type: "Airport",
                  country: "Germany",
                },
                destination: {
                  flightPlaceId: "JFK",
                  displayCode: "JFK",
                  parent: {
                    flightPlaceId: "NYCA",
                    displayCode: "NYC",
                    name: "New York",
                    type: "City",
                  },
                  name: "New York John F. Kennedy",
                  type: "Airport",
                  country: "United States",
                },
                departure: "2025-07-16T19:20:00",
                arrival: "2025-07-16T22:00:00",
                durationInMinutes: 520,
                flightNumber: "601",
                marketingCarrier: {
                  id: -30667,
                  name: "Norse Atlantic Airways",
                  alternateId: "9~",
                  allianceId: 0,
                  displayCode: "N0",
                },
                operatingCarrier: {
                  id: -30667,
                  name: "Norse Atlantic Airways",
                  alternateId: "9~",
                  allianceId: 0,
                  displayCode: "N0",
                },
                transportMode: "TRANSPORT_MODE_FLIGHT",
              },
            ],
          },
        ],
        isSelfTransfer: false,
        isProtectedSelfTransfer: true,
        farePolicy: {
          isChangeAllowed: false,
          isPartiallyChangeable: false,
          isCancellationAllowed: false,
          isPartiallyRefundable: false,
        },
        fareAttributes: {},
        tags: ["cheapest"],
        isMashUp: false,
        hasFlexibleOptions: false,
        score: 0.632178,
      },
      {
        id: "13542-2507161640--31927-1-12712-2507170920",
        price: {
          raw: 860.91,
          formatted: "$861",
          pricingOptionId: "XF_TPoV308U8",
        },
        legs: [
          {
            id: "13542-2507161640--31927-1-12712-2507170920",
            origin: {
              id: "LGW",
              entityId: "95565051",
              name: "London Gatwick",
              displayCode: "LGW",
              city: "London",
              country: "United Kingdom",
              isHighlighted: false,
            },
            destination: {
              id: "JFK",
              entityId: "95565058",
              name: "New York John F. Kennedy",
              displayCode: "JFK",
              city: "New York",
              country: "United States",
              isHighlighted: false,
            },
            durationInMinutes: 1300,
            stopCount: 1,
            isSmallestStops: false,
            departure: "2025-07-16T16:40:00",
            arrival: "2025-07-17T09:20:00",
            timeDeltaInDays: 1,
            carriers: {
              marketing: [
                {
                  id: -31927,
                  alternateId: "AT",
                  logoUrl:
                    "https://logos.skyscnr.com/images/airlines/favicon/AT.png",
                  name: "Royal Air Maroc",
                },
              ],
              operationType: "fully_operated",
            },
            segments: [
              {
                id: "13542-10622-2507161640-2507161955--31927",
                origin: {
                  flightPlaceId: "LGW",
                  displayCode: "LGW",
                  parent: {
                    flightPlaceId: "LOND",
                    displayCode: "LON",
                    name: "London",
                    type: "City",
                  },
                  name: "London Gatwick",
                  type: "Airport",
                  country: "United Kingdom",
                },
                destination: {
                  flightPlaceId: "CMN",
                  displayCode: "CMN",
                  parent: {
                    flightPlaceId: "CASA",
                    displayCode: "CAS",
                    name: "Casablanca",
                    type: "City",
                  },
                  name: "Casablanca Mohamed V.",
                  type: "Airport",
                  country: "Morocco",
                },
                departure: "2025-07-16T16:40:00",
                arrival: "2025-07-16T19:55:00",
                durationInMinutes: 195,
                flightNumber: "803",
                marketingCarrier: {
                  id: -31927,
                  name: "Royal Air Maroc",
                  alternateId: "AT",
                  allianceId: -32000,
                  displayCode: "AT",
                },
                operatingCarrier: {
                  id: -31927,
                  name: "Royal Air Maroc",
                  alternateId: "AT",
                  allianceId: -32000,
                  displayCode: "AT",
                },
                transportMode: "TRANSPORT_MODE_FLIGHT",
              },
              {
                id: "10622-12712-2507170630-2507170920--31927",
                origin: {
                  flightPlaceId: "CMN",
                  displayCode: "CMN",
                  parent: {
                    flightPlaceId: "CASA",
                    displayCode: "CAS",
                    name: "Casablanca",
                    type: "City",
                  },
                  name: "Casablanca Mohamed V.",
                  type: "Airport",
                  country: "Morocco",
                },
                destination: {
                  flightPlaceId: "JFK",
                  displayCode: "JFK",
                  parent: {
                    flightPlaceId: "NYCA",
                    displayCode: "NYC",
                    name: "New York",
                    type: "City",
                  },
                  name: "New York John F. Kennedy",
                  type: "Airport",
                  country: "United States",
                },
                departure: "2025-07-17T06:30:00",
                arrival: "2025-07-17T09:20:00",
                durationInMinutes: 470,
                flightNumber: "202",
                marketingCarrier: {
                  id: -31927,
                  name: "Royal Air Maroc",
                  alternateId: "AT",
                  allianceId: -32000,
                  displayCode: "AT",
                },
                operatingCarrier: {
                  id: -31927,
                  name: "Royal Air Maroc",
                  alternateId: "AT",
                  allianceId: -32000,
                  displayCode: "AT",
                },
                transportMode: "TRANSPORT_MODE_FLIGHT",
              },
            ],
          },
        ],
        isSelfTransfer: false,
        isProtectedSelfTransfer: false,
        farePolicy: {
          isChangeAllowed: false,
          isPartiallyChangeable: false,
          isCancellationAllowed: false,
          isPartiallyRefundable: false,
        },
        fareAttributes: {},
        tags: ["second_cheapest"],
        isMashUp: false,
        hasFlexibleOptions: false,
        score: 0.609274,
      },
      {
        id: "13554-2507161850--31927-1-12712-2507170920",
        price: {
          raw: 903.51,
          formatted: "$904",
          pricingOptionId: "WES7oTCZep-T",
        },
        legs: [
          {
            id: "13554-2507161850--31927-1-12712-2507170920",
            origin: {
              id: "LHR",
              entityId: "95565050",
              name: "London Heathrow",
              displayCode: "LHR",
              city: "London",
              country: "United Kingdom",
              isHighlighted: false,
            },
            destination: {
              id: "JFK",
              entityId: "95565058",
              name: "New York John F. Kennedy",
              displayCode: "JFK",
              city: "New York",
              country: "United States",
              isHighlighted: false,
            },
            durationInMinutes: 1170,
            stopCount: 1,
            isSmallestStops: false,
            departure: "2025-07-16T18:50:00",
            arrival: "2025-07-17T09:20:00",
            timeDeltaInDays: 1,
            carriers: {
              marketing: [
                {
                  id: -31927,
                  alternateId: "AT",
                  logoUrl:
                    "https://logos.skyscnr.com/images/airlines/favicon/AT.png",
                  name: "Royal Air Maroc",
                },
              ],
              operationType: "fully_operated",
            },
            segments: [
              {
                id: "13554-10622-2507161850-2507162210--31927",
                origin: {
                  flightPlaceId: "LHR",
                  displayCode: "LHR",
                  parent: {
                    flightPlaceId: "LOND",
                    displayCode: "LON",
                    name: "London",
                    type: "City",
                  },
                  name: "London Heathrow",
                  type: "Airport",
                  country: "United Kingdom",
                },
                destination: {
                  flightPlaceId: "CMN",
                  displayCode: "CMN",
                  parent: {
                    flightPlaceId: "CASA",
                    displayCode: "CAS",
                    name: "Casablanca",
                    type: "City",
                  },
                  name: "Casablanca Mohamed V.",
                  type: "Airport",
                  country: "Morocco",
                },
                departure: "2025-07-16T18:50:00",
                arrival: "2025-07-16T22:10:00",
                durationInMinutes: 200,
                flightNumber: "807",
                marketingCarrier: {
                  id: -31927,
                  name: "Royal Air Maroc",
                  alternateId: "AT",
                  allianceId: -32000,
                  displayCode: "AT",
                },
                operatingCarrier: {
                  id: -31927,
                  name: "Royal Air Maroc",
                  alternateId: "AT",
                  allianceId: -32000,
                  displayCode: "AT",
                },
                transportMode: "TRANSPORT_MODE_FLIGHT",
              },
              {
                id: "10622-12712-2507170630-2507170920--31927",
                origin: {
                  flightPlaceId: "CMN",
                  displayCode: "CMN",
                  parent: {
                    flightPlaceId: "CASA",
                    displayCode: "CAS",
                    name: "Casablanca",
                    type: "City",
                  },
                  name: "Casablanca Mohamed V.",
                  type: "Airport",
                  country: "Morocco",
                },
                destination: {
                  flightPlaceId: "JFK",
                  displayCode: "JFK",
                  parent: {
                    flightPlaceId: "NYCA",
                    displayCode: "NYC",
                    name: "New York",
                    type: "City",
                  },
                  name: "New York John F. Kennedy",
                  type: "Airport",
                  country: "United States",
                },
                departure: "2025-07-17T06:30:00",
                arrival: "2025-07-17T09:20:00",
                durationInMinutes: 470,
                flightNumber: "202",
                marketingCarrier: {
                  id: -31927,
                  name: "Royal Air Maroc",
                  alternateId: "AT",
                  allianceId: -32000,
                  displayCode: "AT",
                },
                operatingCarrier: {
                  id: -31927,
                  name: "Royal Air Maroc",
                  alternateId: "AT",
                  allianceId: -32000,
                  displayCode: "AT",
                },
                transportMode: "TRANSPORT_MODE_FLIGHT",
              },
            ],
          },
        ],
        isSelfTransfer: false,
        isProtectedSelfTransfer: false,
        farePolicy: {
          isChangeAllowed: false,
          isPartiallyChangeable: false,
          isCancellationAllowed: false,
          isPartiallyRefundable: false,
        },
        fareAttributes: {},
        tags: ["third_cheapest"],
        isMashUp: false,
        hasFlexibleOptions: false,
        score: 0.582793,
      },
      {
        id: "13542-2507161715--31734-1-12712-2507170430",
        price: {
          raw: 980.42,
          formatted: "$981",
          pricingOptionId: "skHkiFHnNNCg",
        },
        legs: [
          {
            id: "13542-2507161715--31734-1-12712-2507170430",
            origin: {
              id: "LGW",
              entityId: "95565051",
              name: "London Gatwick",
              displayCode: "LGW",
              city: "London",
              country: "United Kingdom",
              isHighlighted: false,
            },
            destination: {
              id: "JFK",
              entityId: "95565058",
              name: "New York John F. Kennedy",
              displayCode: "JFK",
              city: "New York",
              country: "United States",
              isHighlighted: false,
            },
            durationInMinutes: 975,
            stopCount: 1,
            isSmallestStops: false,
            departure: "2025-07-16T17:15:00",
            arrival: "2025-07-17T04:30:00",
            timeDeltaInDays: 1,
            carriers: {
              marketing: [
                {
                  id: -31734,
                  alternateId: "TK",
                  logoUrl:
                    "https://logos.skyscnr.com/images/airlines/favicon/TK.png",
                  name: "Turkish Airlines",
                },
              ],
              operationType: "fully_operated",
            },
            segments: [
              {
                id: "13542-12585-2507161715-2507162320--31734",
                origin: {
                  flightPlaceId: "LGW",
                  displayCode: "LGW",
                  parent: {
                    flightPlaceId: "LOND",
                    displayCode: "LON",
                    name: "London",
                    type: "City",
                  },
                  name: "London Gatwick",
                  type: "Airport",
                  country: "United Kingdom",
                },
                destination: {
                  flightPlaceId: "IST",
                  displayCode: "IST",
                  parent: {
                    flightPlaceId: "ISTA",
                    displayCode: "IST",
                    name: "Istanbul",
                    type: "City",
                  },
                  name: "Istanbul",
                  type: "Airport",
                  country: "Türkiye (Turkey)",
                },
                departure: "2025-07-16T17:15:00",
                arrival: "2025-07-16T23:20:00",
                durationInMinutes: 245,
                flightNumber: "1998",
                marketingCarrier: {
                  id: -31734,
                  name: "Turkish Airlines",
                  alternateId: "TK",
                  allianceId: -31999,
                  displayCode: "TK",
                },
                operatingCarrier: {
                  id: -31734,
                  name: "Turkish Airlines",
                  alternateId: "TK",
                  allianceId: -31999,
                  displayCode: "TK",
                },
                transportMode: "TRANSPORT_MODE_FLIGHT",
              },
              {
                id: "12585-12712-2507170050-2507170430--31734",
                origin: {
                  flightPlaceId: "IST",
                  displayCode: "IST",
                  parent: {
                    flightPlaceId: "ISTA",
                    displayCode: "IST",
                    name: "Istanbul",
                    type: "City",
                  },
                  name: "Istanbul",
                  type: "Airport",
                  country: "Türkiye (Turkey)",
                },
                destination: {
                  flightPlaceId: "JFK",
                  displayCode: "JFK",
                  parent: {
                    flightPlaceId: "NYCA",
                    displayCode: "NYC",
                    name: "New York",
                    type: "City",
                  },
                  name: "New York John F. Kennedy",
                  type: "Airport",
                  country: "United States",
                },
                departure: "2025-07-17T00:50:00",
                arrival: "2025-07-17T04:30:00",
                durationInMinutes: 640,
                flightNumber: "111",
                marketingCarrier: {
                  id: -31734,
                  name: "Turkish Airlines",
                  alternateId: "TK",
                  allianceId: -31999,
                  displayCode: "TK",
                },
                operatingCarrier: {
                  id: -31734,
                  name: "Turkish Airlines",
                  alternateId: "TK",
                  allianceId: -31999,
                  displayCode: "TK",
                },
                transportMode: "TRANSPORT_MODE_FLIGHT",
              },
            ],
          },
        ],
        isSelfTransfer: false,
        isProtectedSelfTransfer: false,
        farePolicy: {
          isChangeAllowed: false,
          isPartiallyChangeable: false,
          isCancellationAllowed: false,
          isPartiallyRefundable: false,
        },
        fareAttributes: {},
        isMashUp: false,
        hasFlexibleOptions: false,
        score: 0.580128,
      },
    ],
    messages: [],
    filterStats: {
      duration: {
        min: 470,
        max: 1300,
        multiCityMin: 470,
        multiCityMax: 1300,
      },
      total: 10,
      hasCityOpenJaw: false,
      multipleCarriers: {
        minPrice: "$704",
        rawMinPrice: null,
      },
      airports: [
        {
          city: "London",
          airports: [
            {
              id: "LGW",
              entityId: "95565051",
              name: "London Gatwick",
            },
            {
              id: "LHR",
              entityId: "95565050",
              name: "London Heathrow",
            },
            {
              id: "STN",
              entityId: "95565052",
              name: "London Stansted",
            },
          ],
        },
        {
          city: "New York",
          airports: [
            {
              id: "JFK",
              entityId: "95565058",
              name: "New York John F. Kennedy",
            },
            {
              id: "EWR",
              entityId: "95565059",
              name: "New York Newark",
            },
          ],
        },
      ],
      carriers: [
        {
          id: -32171,
          alternateId: "B6",
          logoUrl: "https://logos.skyscnr.com/images/airlines/favicon/B6.png",
          name: "jetBlue",
          minPrice: "$1,262",
          allianceId: 0,
        },
        {
          id: -30667,
          alternateId: "9~",
          logoUrl: "https://logos.skyscnr.com/images/airlines/favicon/9%7E.png",
          name: "Norse Atlantic Airways",
          allianceId: 0,
        },
        {
          id: -30598,
          alternateId: "I)",
          logoUrl: "https://logos.skyscnr.com/images/airlines/favicon/I%29.png",
          name: "Norse Atlantic Airways (UK)",
          minPrice: "$1,349",
          allianceId: 0,
        },
        {
          id: -31927,
          alternateId: "AT",
          logoUrl: "https://logos.skyscnr.com/images/airlines/favicon/AT.png",
          name: "Royal Air Maroc",
          minPrice: "$861",
          allianceId: -32000,
        },
        {
          id: -31915,
          alternateId: "FR",
          logoUrl: "https://logos.skyscnr.com/images/airlines/favicon/FR.png",
          name: "Ryanair",
          allianceId: 0,
        },
        {
          id: -31901,
          alternateId: "SK",
          logoUrl: "https://logos.skyscnr.com/images/airlines/favicon/SK.png",
          name: "Scandinavian Airlines",
          minPrice: "$921",
          allianceId: -31998,
        },
        {
          id: -31734,
          alternateId: "TK",
          logoUrl: "https://logos.skyscnr.com/images/airlines/favicon/TK.png",
          name: "Turkish Airlines",
          minPrice: "$981",
          allianceId: -31999,
        },
      ],
      stopPrices: {
        direct: {
          isPresent: true,
          formattedPrice: "$1,262",
          rawPrice: 1262,
        },
        one: {
          isPresent: true,
          formattedPrice: "$704",
          rawPrice: 704,
        },
        twoOrMore: {
          isPresent: false,
        },
      },
      alliances: [
        {
          id: -32000,
          name: "OneWorld",
        },
        {
          id: -31999,
          name: "Star Alliance",
        },
        {
          id: -31998,
          name: "SkyTeam",
        },
      ],
    },
    flightsSessionId: "5d40f1bb-d710-4088-9f25-bcef21ec9198",
    destinationImageUrl:
      "https://content.skyscnr.com/m/3719e8f4a5daf43d/original/Flights-Placeholder.jpg",
  },
};
